In [1]:
from utils.analyse_results import GraphsTraining, Results, load_all_pickles, plot_time_bands

train_info = GraphsTraining()

In [2]:
results_reg_norm = load_all_pickles("results/study_vdp/pyomo_network_size/reg_norm", recursive=False)
results_reg_norm_df = Results.flatten_convergence_data(results_reg_norm, key_list=["system", "reg", "tol"], model_type="pyomo")

# results_no_reg_norm = load_all_pickles("results/study_vdp/pyomo_network_size/pyomo_ho_32_190126", recursive=False)
# results_no_reg_norm_df = Results.flatten_convergence_data(results_no_reg_norm, key_list=["system", "reg", "tol"], model_type="pyomo")

Loaded results/study_vdp/pyomo_network_size/reg_norm/1479179201_2026-01-25_14-04.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/1793250036_2026-01-25_14-21.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/1803414593_2026-01-25_14-17.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/1973013475_2026-01-25_14-50.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/1987511618_2026-01-25_15-02.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/2001300514_2026-01-25_14-40.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/2209426783_2026-01-25_14-55.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/2561250187_2026-01-25_14-24.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/2862791915_2026-01-25_15-11.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/3411392939_2026-01-25_14-31.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/3507323423_2026-01-25_14-36.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/575476294_2026-01-25_15-07.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/744346216_2026-01-25_14-07.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/82706259_2026-01-25_14-46.pkl
Loaded results/study_vdp/pyomo_network_size/reg_norm/937548045_2026-01-25_14-13.pkl

Loaded 15 files from results/study_vdp/pyomo_network_size/reg_norm

In [10]:
results_reg_norm_df.sort_values("time_elapsed").tail(20)

,system,reg,tol,time_elapsed,direct_model_pred,odeint_pred,odeint_pred_test,mse_train,mse_test,mse_train_coll,mse_test_coll,termination,seed
5,"(2, 96, 2)",0.1,1.000000e-08,29.734508,"[[0.0, 0.0005649607426847258, 0.00293219185248...","[[0.0, 1.0], [0.0005573937, 1.0010194], [0.002...","[[1.9083185, -0.77511317], [1.9068673, -0.7754...",0.095754,7.010920,0.492837,6.908942,optimal,575476294
5,"(2, 96, 2)",0.1,1.000000e-08,30.495855,"[[0.0, 0.0007537305098602006, 0.00377217504405...","[[0.0, 1.0], [0.0007250719, 1.0008231], [0.003...","[[1.9083185, -0.77511317], [1.906448, -0.77524...",0.037759,7.101147,0.035034,6.587340,optimal,1973013475
5,"(2, 96, 2)",0.1,1.000000e-08,31.220588,"[[0.0, 0.0007796978282834275, 0.00404130762425...","[[0.0, 1.0], [0.00077070214, 1.0009621], [0.00...","[[1.9083185, -0.77511317], [1.9066145, -0.7757...",0.035822,0.794374,0.002293,0.176678,optimal,744346216
5,"(2, 96, 2)",0.1,1.000000e-08,36.057471,"[[0.0, 0.0003762660403735605, 0.00198921605645...","[[0.0, 1.0], [0.0003761481, 1.0008929], [0.001...","[[1.9083185, -0.77511317], [1.9068925, -0.7760...",0.002130,0.745867,0.002114,0.701175,optimal,2862791915
4,"(2, 64, 2)",0.1,1.000000e-08,36.920571,"[[5.576234340324287e-19, 0.0005398171494369575...","[[0.0, 1.0], [0.00052989426, 1.0009711], [0.00...","[[1.9083185, -0.77511317], [1.9068469, -0.7754...",3.499641,179.046829,2.246994,4.602850,optimal,1793250036
3,"(2, 32, 2)",0.1,1.000000e-08,38.653478,"[[0.0, 0.0006045977819473585, 0.00324160984676...","[[0.0, 1.0], [0.00061346684, 1.0012738], [0.00...","[[1.9083185, -0.77511317], [1.9063411, -0.7757...",0.466608,2.260023,0.538334,2.192389,optimal,744346216
4,"(2, 64, 2)",0.1,1.000000e-08,41.711371,"[[-1.4264904230167238e-19, 0.00035631414870398...","[[0.0, 1.0], [0.00035624037, 1.0008903], [0.00...","[[1.9083185, -0.77511317], [1.9068456, -0.7762...",0.005686,0.908167,2.860228,0.831218,optimal,3507323423
5,"(2, 96, 2)",0.1,1.000000e-08,43.694416,"[[0.0, 0.000721021817249781, 0.003892114645752...","[[0.0, 1.0], [0.0007356603, 1.0011125], [0.003...","[[1.9083185, -0.77511317], [1.9066497, -0.7757...",0.031555,2.066950,0.198992,2.144854,optimal,1793250036
5,"(2, 96, 2)",0.1,1.000000e-08,45.825415,"[[0.0, 0.000377251989449941, 0.001993978423782...","[[0.0, 1.0], [0.00037706684, 1.0008893], [0.00...","[[1.9083185, -0.77511317], [1.9068925, -0.7760...",0.002276,0.793698,0.002135,0.707471,optimal,1479179201
4,"(2, 64, 2)",0.1,1.000000e-08,47.583016,"[[3.843302061637466e-19, 0.000662589722921894,...","[[0.0, 1.0], [0.00068074826, 1.0010808], [0.00...","[[1.9083185, -0.77511317], [1.9066268, -0.7756...",0.698027,430.220459,0.609441,4.485702,optimal,2862791915
0,"(2, 4, 2)",0.1,1.000000e-08,55.236297,"[[-5.6142185213855446e-18, 0.00083169683154365...","[[0.0, 1.0], [0.00083174877, 1.001092], [0.004...","[[1.9083185, -0.77511317], [1.907321, -0.77732...",0.087468,1.250174,0.083786,1.279408,optimal,82706259
5,"(2, 96, 2)",0.1,1.000000e-08,60.099704,"[[0.0, 0.0007532406421792986, 0.00378051945519...","[[0.0, 1.0], [0.000726449, 1.0011016], [0.0038...","[[1.9083185, -0.77511317], [1.9066399, -0.7757...",1.329105,1.402261,0.112397,1.688047,optimal,1803414593
4,"(2, 64, 2)",0.1,1.000000e-08,60.143229,"[[-4.586463074660446e-18, 0.000377132574620799...","[[0.0, 1.0], [0.0003769127, 1.0008789], [0.001...","[[1.9083185, -0.77511317], [1.9068573, -0.7761...",0.005794,0.809879,2.896098,0.796472,optimal,2561250187
5,"(2, 96, 2)",0.1,1.000000e-08,60.441029,"[[0.0, 0.0007575970938839694, 0.00393037488917...","[[0.0, 1.0], [0.0007494845, 1.0011232], [0.003...","[[1.9083185, -0.77511317], [1.9067259, -0.7758...",5.170225,2.140917,0.592546,2.317195,optimal,3507323423
4,"(2, 64, 2)",0.1,1.000000e-08,74.829952,"[[0.0, 0.00037653254973661133, 0.0019892621290...","[[0.0, 1.0], [0.00037632047, 1.0008775], [0.00...","[[1.9083185, -0.77511317], [1.9068645, -0.7761...",0.006389,0.986893,0.002711,0.800741,optimal,2209426783
4,"(2, 64, 2)",0.1,1.000000e-08,119.838093,"[[0.0, 0.0003611951145173881, 0.00190985386169...","[[0.0, 1.0], [0.00036112792, 1.0008761], [0.00...","[[1.9083185, -0.77511317], [1.9068767, -0.7761...",0.002753,1.143277,2.891449,0.780508,optimal,575476294
4,"(2, 64, 2)",0.1,1.000000e-08,179.977391,"[[0.0, 0.0003623887793085893, 0.00191682037679...","[[0.0, 1.0], [0.00036237773, 1.000905], [0.001...","[[1.9083185, -0.77511317], [1.9068272, -0.7762...",0.002785,0.464785,0.002736,0.874924,optimal,82706259
4,"(2, 64, 2)",0.1,1.000000e-08,197.003019,"[[0.0, 0.0003692756316457213, 0.00195341177083...","[[0.0, 1.0], [0.0003693146, 1.0009149], [0.001...","[[1.9083185, -0.77511317], [1.9068263, -0.7762...",0.002807,1.088941,0.002673,0.882267,optimal,937548045
4,"(2, 64, 2)",0.1,1.000000e-08,234.660991,"[[0.0, 0.00036328341904175854, 0.0019216304323...","[[0.0, 1.0], [0.00036328312, 1.0009099], [0.00...","[[1.9083185, -0.77511317], [1.9068259, -0.7762...",0.002810,0.783755,0.002715,0.885242,optimal,3411392939
4,"(2, 64, 2)",0.1,1.000000e-08,267.690817,"[[0.0, 0.0005860231561733032, 0.00303824965363...","[[0.0, 1.0], [0.00057829847, 1.0009733], [0.00...","[[1.9083185, -0.77511317], [1.9067584, -0.7755...",0.084264,38.950500,0.019756,3.226605,optimal,1987511618

In [11]:
results_reg_norm_df.groupby("system")[["time_elapsed", "mse_train_coll", "mse_test_coll"]].min()

            time_elapsed  mse_train_coll  mse_test_coll
system
(2, 4, 2)       3.422591        0.073654       1.132868
(2, 8, 2)       4.511253        0.016286       0.954775
(2, 16, 2)      3.705225        0.007991       0.396354
(2, 32, 2)      7.063172        0.004275       0.224801
(2, 64, 2)     15.402262        0.002673       0.599275
(2, 96, 2)     18.987859        0.002114       0.176678

In [16]:
results_no_reg_norm_df.groupby("system")[["time_elapsed", "mse_train_coll", "mse_test_coll"]].mean()

            time_elapsed  mse_train_coll  mse_test_coll
system
(2, 4, 2)       3.819714        0.070303       0.126268
(2, 8, 2)      28.645436        0.028089       0.040762
(2, 16, 2)     30.892113        0.004038       0.007613
(2, 32, 2)     51.439840        0.075595       0.095627
(2, 64, 2)     56.132313        0.027909       0.036314
(2, 96, 2)     13.734692        0.075612       0.095435